from dotenv import dotenv_values

from src.utils import pegar_data_hora


def get_env(chave, caminho_env, padrao=None):
    _config = dotenv_values(caminho_env)
    return _config.get(chave, padrao)

CAMINHO_CONFIG_ENV = r'.\envs\GCPJ_inclusao\config.env'

CAMINHO_ARQ_JAR = get_env('CAMINHO_ARQ_JAR', CAMINHO_CONFIG_ENV)
CAMINHO_DIR_JAR = get_env('CAMINHO_DIR_JAR', CAMINHO_CONFIG_ENV)

URL_GCPJ = get_env('URL_GCPJ', CAMINHO_CONFIG_ENV)

CAMINHO_CERT = get_env('CAMINHO_CERT', CAMINHO_CONFIG_ENV)
CAMINHO_PASTA_DOCUMENTOS_GCPJ = get_env('CAMINHO_PASTA_DOCUMENTOS_GCPJ', CAMINHO_CONFIG_ENV)
CAMINHO_PASTA_PLANILHA_BASE_GCPJ = get_env('CAMINHO_PASTA_PLANILHA_BASE_GCPJ', CAMINHO_CONFIG_ENV)

CAMINHO_CONCLUIDOS = get_env('CAMINHO_CONCLUIDOS', CAMINHO_CONFIG_ENV)
CAMINHO_PASTA_LOTES_MULTIPAG = get_env('CAMINHO_PASTA_LOTES_MULTIPAG', CAMINHO_CONFIG_ENV)
CAMINHO_PASTA_BAIXADOS_DIVERSOS = get_env('CAMINHO_PASTA_BAIXADOS_DIVERSOS', CAMINHO_CONFIG_ENV)